version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: coworking_postgres
    environment:
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coworking_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: