version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: coworking_postgres
    environment:
      POSTGRES_USER: alibi
      POSTGRES_PASSWORD: alibi
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
